# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = net.bensome01
archives_name = vegan_plants
enabled_platforms = neoforge

# Minecraft properties
minecraft_version = 1.21.1

#
forgeconfigapiport_version=21.1.3

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.19.2
neoforge_version = 21.1.215

